// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKxR-xhg9FLJCQCH5eZy4p5Aos5atHtsE',
    appId: '1:241957845106:web:b28e91df32556dcf562aeb',
    messagingSenderId: '241957845106',
    projectId: 'flush-chat-17b91',
    authDomain: 'flush-chat-17b91.firebaseapp.com',
    storageBucket: 'flush-chat-17b91.firebasestorage.app',
    measurementId: 'G-R041BVTM3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Lp1YLUb1uORkLf1cJ-TnhV1YQnKoc7s',
    appId: '1:241957845106:android:71ad80b872ab13f5562aeb',
    messagingSenderId: '241957845106',
    projectId: 'flush-chat-17b91',
    storageBucket: 'flush-chat-17b91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpB06MWEUoNtMmcs-NEECwL_2noyWsT24',
    appId: '1:241957845106:ios:fab439e3c052706e562aeb',
    messagingSenderId: '241957845106',
    projectId: 'flush-chat-17b91',
    storageBucket: 'flush-chat-17b91.firebasestorage.app',
    iosBundleId: 'com.example.photoBezaGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpB06MWEUoNtMmcs-NEECwL_2noyWsT24',
    appId: '1:241957845106:ios:fab439e3c052706e562aeb',
    messagingSenderId: '241957845106',
    projectId: 'flush-chat-17b91',
    storageBucket: 'flush-chat-17b91.firebasestorage.app',
    iosBundleId: 'com.example.photoBezaGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKxR-xhg9FLJCQCH5eZy4p5Aos5atHtsE',
    appId: '1:241957845106:web:1300f83ec87a9580562aeb',
    messagingSenderId: '241957845106',
    projectId: 'flush-chat-17b91',
    authDomain: 'flush-chat-17b91.firebaseapp.com',
    storageBucket: 'flush-chat-17b91.firebasestorage.app',
    measurementId: 'G-691M7XLZTK',
  );

}